svr_config:
  port: 8002
  name: "commentsvr"
  host: "124.220.156.104"

log:
  level: "debug"
  file_name: "commentsvr.log"
  log_path: "../../log/commentsvr/"
  max_size: 200
  max_age: 30
  max_backups: 7


consul:
  host: "124.220.156.104"
  port: 8500
  tags:
    - "commentsvr"

mysql:
  username: "root"
  password: "123456"
  host: "124.220.156.104"
  port: "8086"
  database: "mini_tiktok"
  max_idle_conn: 10
  max_open_conn: 100
  max_idle_time: 3600

redis:
  host: "124.220.156.104"
  password: "123456"
  db: 0
  port: 6379
  pool_size: 10
  expired: 120

