ping: "hello world"

svr_config:
  port: 8005
  mode: "dev"
  host: "124.220.156.104"
  video_path: "/root/tiktok/video"
  user_svr_name: "usersvr"
  video_svr_name: "videosvr"
  favorite_svr_name: "favoritesvr"
  relation_svr_name: "relationsvr"
  comment_svr_name: "commentsvr"
  message_svr_name: "messagesvr"


log:
  level: "debug"
  file_name: "gatewaysvr.log"
  log_path: "../../log/gatawaysvr/"
  max_size: 200
  max_age: 30
  max_backups: 7

consul:
    host: "124.220.156.104"
    port: 8500
    tags:
      - "gatewaysvr"


