svr_config:
  port: 8001
  name: "relationsvr"
  host: "124.220.156.104"

log:
  level: "debug"
  file_name: "relationsvr.log"
  log_path: "../../log/relationsvr/"
  max_size: 200
  max_age: 30
  max_backups: 7


consul:
    host: "124.220.156.104"
    port: 8500
    tags:
      - "relationsvr"

mysql:
    username: "root"
    password: "123456"
    host: "124.220.156.104"
    port: "8086"
    database: "mini_tiktok"
    max_idle_conn: 10
    max_open_conn: 100
    max_idle_time: 3600


