svr_config:
  port: 8004
  name: "videosvr"
  host: "124.220.156.104"


log:
  level: "debug"
  file_name: "videosvr.log"
  log_path: "../../log/videosvr/"
  max_size: 200
  max_age: 30
  max_backups: 7


consul:
    host: "124.220.156.104"
    port: 8500
    tags:
      - "usersvr"

mysql:
    username: "root"
    password: "123456"
    host: "124.220.156.104"
    port: "8086"
    database: "mini_tiktok"
    max_idle_conn: 10
    max_open_conn: 100
    max_idle_time: 3600

redis:
  host: "124.220.156.104"
  password: "123456"
  db: 0
  port: 6379
  pool_size: 10
  expired: 120


minio:
  host: "124.220.156.104"
  port: "9000"
  access_key_id: "mAVisPmIZNA1d9bt6ENW"
  secret_access_key: "xDygOlvOFErjCrX1gm8oEVICUCY2bJVVyB5lwogL"
  video_buckets: video
  pic_buckets: pic
  video_path: "/root/tiktok/video"
  pic_path: "/root/tiktok/pic"